export const project = {
  allowDonations: true,
  classification: 'large-scale-planting',
  countPlanted: 2811,
  countTarget: 12500000,
  country: 'PE',
  currency: 'NGN',
  id: 'proj_sMTZsx6uBCgY0j7adKjJ3G11',
  image: '5e294644e55b4387545750.jpg',
  isFeatured: true,
  isPublished: true,
  location: 'Andes region, South America (Colombia, Ecuador, Peru, Bolivia, Argentina, Chile)',
  minTreeCount: 1,
  name: 'Acción Andina - Andes Action',
  paymentDefaults: { fixedDefaultTreeCount: 5, fixedTreeCountOptions: Array(4) },
  reviewScore: 0,
  slug: 'accion-andina-andes-action',
  taxDeductionCountries: ['DE', 'US'],
  tpo: {
    id: 'tpo_6t3q5JNUtHPCvXVfrArIRDf7', name: 'Global Forest Generation', email: 'info@globalforestgen.org', slug: 'global-forest-generation',
  },
  treeCost: 760.99,
};
