-- auto-generated definition
create table destination_transaction
(
    id                             integer generated by default as identity
        primary key,
    provider_reference             varchar(255) not null,
    destination                    varchar(16)  not null,
    purpose                        varchar(64)  not null,
    type                           varchar(32)  not null,
    payment_type                   varchar(255) default NULL::character varying,
    operation_date                 timestamp(0) not null,
    payment_gateway                varchar(32)  not null,
    project_currency               varchar(255) default NULL::character varying,
    project_exchange_rate          double precision,
    exchange_rate                  double precision,
    source_currency                varchar(3)   not null,
    target_currency                varchar(3)   not null,
    source_amount                  integer      not null,
    target_amount                  integer      not null,
    source_fee                     integer,
    target_fee                     integer,
    unit_cost                      double precision,
    units                          bigint,
    prevent_payout                 boolean      not null,
    payout_note                    text,
    is_consolidated                boolean      not null,
    is_paid_out                    boolean      not null,
    financial_transaction_id       integer,
    position                       integer,
    created                        timestamp(0) not null,
    updated                        timestamp(0) not null,
    deleted_at                     timestamp(0) default NULL::timestamp without time zone,
    subscription_id                integer
        constraint fk_5705eeea9a1887dc
            references payment_recurrency,
    donation_id                    integer
        constraint fk_5705eeea4dc1279c
            references donation,
    platform_payout_id             integer
        constraint fk_5705eeea35ea1a37
            references platform_payout,
    account_transaction_id         integer
        constraint fk_5705eeea7d370f05
            references account_transaction,
    planet_cash_transaction_id     integer
        constraint fk_5705eeea22ef4879
            references planet_cash_transaction,
    planet_cash_account_id         integer
        constraint fk_5705eeea8d7d2b2
            references planet_cash_account,
    ro_account_id                  integer
        constraint fk_5705eeea1cbd621a
            references ro_account,
    project_id                     integer
        constraint fk_5705eeea166d1f9c
            references project,
    project_plan_id                integer
        constraint fk_5705eeea7e870efe
            references project_plan,
    related_payment_transaction_id integer
        constraint fk_5705eeea7affc66a
            references destination_transaction,
    created_by                     integer
        constraint fk_5705eeeade12ab56
            references fos_user,
    updated_by                     integer
        constraint fk_5705eeea16fe72e1
            references fos_user
);

alter table destination_transaction
    owner to postgres;

create index idx_5705eeea9a1887dc
    on destination_transaction (subscription_id);

create index idx_5705eeea4dc1279c
    on destination_transaction (donation_id);

create index idx_5705eeea35ea1a37
    on destination_transaction (platform_payout_id);

create index idx_5705eeea7d370f05
    on destination_transaction (account_transaction_id);

create index idx_5705eeea22ef4879
    on destination_transaction (planet_cash_transaction_id);

create index idx_5705eeea8d7d2b2
    on destination_transaction (planet_cash_account_id);

create index idx_5705eeea1cbd621a
    on destination_transaction (ro_account_id);

create index idx_5705eeea166d1f9c
    on destination_transaction (project_id);

create index idx_5705eeea7e870efe
    on destination_transaction (project_plan_id);

create unique index uniq_5705eeea7affc66a
    on destination_transaction (related_payment_transaction_id);

create index idx_5705eeeade12ab56
    on destination_transaction (created_by);

create index idx_5705eeea16fe72e1
    on destination_transaction (updated_by);

