-- auto-generated definition
create table donation
(
    id                     integer generated by default as identity
        primary key,
    source                 varchar(64)  default NULL::character varying,
    idempotency_key        varchar(64)  default NULL::character varying,
    uid                    varchar(50)  default NULL::character varying,
    token                  varchar(50)  default NULL::character varying,
    donor_alias            varchar(255) default NULL::character varying,
    locale                 varchar(2)   default NULL::character varying,
    amount                 bigint       not null,
    tax                    integer,
    fee                    integer,
    currency               varchar(3)   not null,
    recurrency_mnemonic    varchar(20)  default NULL::character varying,
    gift_method            varchar(20)  default NULL::character varying,
    publish_profile        boolean      not null,
    is_finalized           boolean      not null,
    tax_deduction_country  varchar(20)  default NULL::character varying,
    purpose                varchar(32)  not null,
    bouquet_purpose        varchar(16)  default NULL::character varying,
    on_behalf              boolean,
    donor_comment          varchar(255) default NULL::character varying,
    comment                text,
    payment_type           varchar(32)  default NULL::character varying,
    gift_data              jsonb,
    line_item_data         jsonb,
    metadata               jsonb,
    payment_country        varchar(2)   default NULL::character varying,
    origin                 varchar(50)  default NULL::character varying,
    archived               boolean,
    sf_opportunity_id      varchar(64)  default NULL::character varying,
    deleted_at             timestamp(0) default NULL::timestamp without time zone,
    guid                   varchar(32)  not null,
    created                timestamp(0) not null,
    updated                timestamp(0) not null,
    session_id             varchar(64)  default NULL::character varying,
    fundraiser_id          integer
        constraint fk_31e581a09f4d1df6
            references fundraiser,
    profile_id             integer
        constraint fk_31e581a0ccfa12b8
            references profile,
    tenant_id              integer
        constraint fk_31e581a09033212a
            references tenant,
    payment_recurrency_id  integer
        constraint fk_31e581a0cb8aad02
            references payment_recurrency,
    planet_cash_account_id integer
        constraint fk_31e581a08d7d2b2
            references planet_cash_account,
    project_id             integer
        constraint fk_31e581a0166d1f9c
            references project,
    bouquet_donation_id    integer,
    receipt_address_id     integer
        constraint fk_31e581a0f94119e
            references address,
    donation_statement_id  integer
        constraint fk_31e581a0e7e27f7c
            references donation_statement,
    receipt_id             integer
        constraint fk_31e581a02b5ca896
            references donation_receipt,
    created_by             integer
        constraint fk_31e581a0de12ab56
            references fos_user,
    updated_by             integer
        constraint fk_31e581a016fe72e1
            references fos_user
);

alter table donation
    owner to postgres;

create unique index uniq_31e581a0539b0606
    on donation (uid);

create unique index uniq_31e581a05f37a13b
    on donation (token);

create unique index uniq_31e581a02b6fcfb2
    on donation (guid);

create index idx_31e581a09f4d1df6
    on donation (fundraiser_id);

create index idx_31e581a0ccfa12b8
    on donation (profile_id);

create index idx_31e581a09033212a
    on donation (tenant_id);

create index idx_31e581a0cb8aad02
    on donation (payment_recurrency_id);

create index idx_31e581a08d7d2b2
    on donation (planet_cash_account_id);

create index idx_31e581a0166d1f9c
    on donation (project_id);

create index idx_31e581a0f94119e
    on donation (receipt_address_id);

create index idx_31e581a0e7e27f7c
    on donation (donation_statement_id);

create unique index uniq_31e581a02b5ca896
    on donation (receipt_id);

create index idx_31e581a0de12ab56
    on donation (created_by);

create index idx_31e581a016fe72e1
    on donation (updated_by);

