-- auto-generated definition
create table payment
(
    fee                               integer,
    tax                               integer,
    account_type                      varchar(32)  default NULL::character varying,
    id                                integer generated by default as identity
        primary key,
    origin                            varchar(50)  default NULL::character varying,
    payment_type                      varchar(32)  default NULL::character varying,
    country                           varchar(2)   default NULL::character varying,
    source_amount                     bigint      not null,
    target_amount                     bigint,
    source_currency                   varchar(3)  not null,
    target_currency                   varchar(3)   default NULL::character varying,
    exchange_rate                     double precision,
    gateway                           varchar(20)  default NULL::character varying,
    method                            varchar(20)  default NULL::character varying,
    reference                         varchar(255) default NULL::character varying,
    refund_reference                  varchar(255) default NULL::character varying,
    status                            varchar(20) not null,
    payment_request                   jsonb,
    payment_response                  jsonb,
    provider_artifact                 jsonb,
    payment_date                      timestamp(0) default NULL::timestamp without time zone,
    refund_date                       timestamp(0) default NULL::timestamp without time zone,
    event_audit_log                   jsonb,
    donation_id                       integer     not null
        constraint fk_6d28840d4dc1279c
            references donation,
    account_payment_transaction_id    integer
        constraint fk_6d28840d293e6351
            references account_transaction,
    account_refund_transaction_id     integer
        constraint fk_6d28840d1c8349c6
            references account_transaction,
    planet_cash_charge_transaction_id integer
        constraint fk_6d28840d95ce19d
            references planet_cash_transaction,
    planet_cash_refund_transaction_id integer
        constraint fk_6d28840dffde221
            references planet_cash_transaction,
    payment_account_id                integer
        constraint fk_6d28840dae9dde6f
            references payment_account,
    planet_cash_account_id            integer
        constraint fk_6d28840d8d7d2b2
            references planet_cash_account
);

alter table payment
    owner to postgres;

create unique index uniq_6d28840d4dc1279c
    on payment (donation_id);

create unique index uniq_6d28840d293e6351
    on payment (account_payment_transaction_id);

create unique index uniq_6d28840d1c8349c6
    on payment (account_refund_transaction_id);

create unique index uniq_6d28840d95ce19d
    on payment (planet_cash_charge_transaction_id);

create unique index uniq_6d28840dffde221
    on payment (planet_cash_refund_transaction_id);

create index idx_6d28840dae9dde6f
    on payment (payment_account_id);

create index idx_6d28840d8d7d2b2
    on payment (planet_cash_account_id);

create index idx_payment_reference
    on payment (reference);

