-- auto-generated definition
create table project_contribution
(
    id                         integer generated by default as identity
        primary key,
    donation_id                integer
        constraint fk_c092fa764dc1279c
            references donation,
    units                      bigint       not null,
    purpose                    varchar(64)  not null,
    unit_type                  varchar(255) not null,
    currency                   varchar(3)   default NULL::character varying,
    units_allocated            integer,
    allocation_priority        varchar(16)  not null,
    created                    timestamp(0) not null,
    updated                    timestamp(0) not null,
    deleted_at                 timestamp(0) default NULL::timestamp without time zone,
    project_id                 integer      not null
        constraint fk_c092fa76166d1f9c
            references project,
    destination_transaction_id integer
        constraint fk_c092fa7672a3bafc
            references destination_transaction,
    profile_id                 integer
        constraint fk_c092fa76ccfa12b8
            references profile,
    created_by                 integer
        constraint fk_c092fa76de12ab56
            references fos_user,
    updated_by                 integer
        constraint fk_c092fa7616fe72e1
            references fos_user
);

alter table project_contribution
    owner to postgres;

create index idx_c092fa76166d1f9c
    on project_contribution (project_id);

create unique index uniq_c092fa7672a3bafc
    on project_contribution (destination_transaction_id);

create index idx_c092fa76ccfa12b8
    on project_contribution (profile_id);

create index idx_c092fa764dc1279c
    on project_contribution (donation_id);

create index idx_c092fa76de12ab56
    on project_contribution (created_by);

create index idx_c092fa7616fe72e1
    on project_contribution (updated_by);

