-- auto-generated definition
create table contribution
(
    id                     integer generated by default as identity
        primary key,
    tpo_id                 integer
        references profile,
    plant_project_id       integer
        references project,
    tpo_recipient_proxy_id integer
        references tpo_donor_proxy,
    tpo_donor_proxy_id     integer
        references tpo_donor_proxy,
    receipt_id             integer
        references donation_receipt,
    contribution_type      varchar(20) not null,
    tree_count             numeric(14, 2),
    plant_date             timestamp,
    tree_type              varchar(255),
    is_confirmed           boolean     not null,
    is_verified            smallint,
    created                timestamp   not null,
    updated                timestamp   not null,
    deleted_at             timestamp,
    is_dirty               boolean,
    discr                  varchar(20) not null,
    remote_project_uid     varchar(255),
    remote_recipient_uid   varchar(255),
    tree_classification    varchar(255),
    tree_scientific_name   varchar(255),
    tree_species           text,
    geo_longitude          double precision,
    geo_latitude           double precision,
    country                varchar(5),
    uid                    varchar(50),
    remote_donor_uid       varchar(255),
    remote_id              varchar(255),
    remote_uid             varchar(255),
    amount                 numeric(10, 2),
    currency               varchar(3),
    gift_method            varchar(20),
    payment_method         varchar(20),
    payment_options        json,
    is_paid                boolean,
    payment_details        jsonb,
    origin                 varchar(50),
    token                  varchar(50),
    payment_status         varchar(20),
    created_by             integer
        references fos_user,
    updated_by             integer
        references fos_user,
    payment_id             varchar(255),
    recurrency_mnemonic    varchar(20),
    geometry               json,
    context                varchar(255),
    comment                text,
    payment_recurrency_id  integer
        references payment_recurrency,
    is_finalized           boolean,
    tenant_id              integer
        references tenant,
    guid                   varchar(32) not null,
    user_description       text,
    verification_status    varchar(32),
    verification_sources   text,
    tax_deduction_country  varchar(20),
    payment_account_id     integer
        references payment_account,
    tax_receipt            json,
    dtn_issue_date         timestamp,
    dtn                    varchar(64),
    dtn_cancellation_code  varchar(64),
    dtn_cancellation_date  timestamp,
    unit_cost              double precision,
    donor_alias            varchar(255),
    on_behalf              boolean,
    planet_cash_account_id integer
        references planet_cash_account,
    profile_id             integer
        references profile,
    idempotency_key        varchar(64),
    purpose                varchar(16),
    gateway                varchar(20),
    method                 varchar(20),
    publish_profile        boolean,
    trees_allocated        integer,
    allocation_priority    varchar(16),
    allocation_notified    timestamp,
    project_plan_id        integer
        references project_plan,
    quantity               double precision,
    bouquet_donation_id    integer
        references contribution,
    fee                    integer,
    donor_absorbs_fee      boolean,
    bouquet_purpose        varchar(16),
    metadata               jsonb,
    target_amount          integer,
    target_currency        varchar(3),
    project_currency       varchar(3),
    project_exchange_rate  double precision,
    gift_data              json,
    donor_comment          varchar(255),
    payment_type           varchar(32),
    session_id             varchar(64),
    line_items             json,
    remote_connection      varchar(32),
    payment_country        varchar(2),
    dtn_issuer_id          integer
        references fos_user,
    project_finalized_id   integer
        references project,
    unit_type              varchar(255),
    archived               boolean,
    sf_opportunity_id      varchar(64),
    tax                    integer,
    receipt_address_id     integer
        references address,
    donation_statement_id  integer
        constraint fk_ea351e15e7e27f7c
            references donation_statement,
    fundraiser_id          integer
        constraint fk_ea351e159f4d1df6
            references fundraiser
);

alter table contribution
    owner to u16et197rmd1g5;

create index idx_ea351e151ad1f991
    on contribution (bouquet_donation_id);

create index idx_ea351e15de12ab56
    on contribution (created_by);

create index contribution_discr_idx
    on contribution (discr);

create index dtn_idx
    on contribution (dtn);

create index idx_ea351e15f15b577a
    on contribution (dtn_issuer_id);

create unique index uniq_ea351e152b6fcfb2
    on contribution (guid);

create index contribution_idempotency_idx
    on contribution (idempotency_key);

create index idx_ea351e15ae9dde6f
    on contribution (payment_account_id);

create index payment_id_idx
    on contribution (payment_id);

create index idx_ea351e15cb8aad02
    on contribution (payment_recurrency_id);

create unique index planet_cash_idempotency
    on contribution (planet_cash_account_id, idempotency_key);

create index idx_ea351e158d7d2b2
    on contribution (planet_cash_account_id);

create index idx_ea351e15e83c4879
    on contribution (plant_project_id);

create index idx_ea351e15ccfa12b8
    on contribution (profile_id);

create index idx_ea351e1576f7f453
    on contribution (project_finalized_id);

create index idx_ea351e157e870efe
    on contribution (project_plan_id);

create index idx_ea351e15f94119e
    on contribution (receipt_address_id);

create index idx_ea351e152b5ca896
    on contribution (receipt_id);

create unique index unique_connection_remoteid
    on contribution (remote_connection, remote_id);

create index remote_id_idx
    on contribution (remote_id);

create index remote_uid_idx
    on contribution (remote_uid);

create index idx_ea351e159033212a
    on contribution (tenant_id);

create unique index uniq_ea351e155f37a13b
    on contribution (token);

create index idx_ea351e1525af33f6
    on contribution (tpo_donor_proxy_id);

create index idx_ea351e1522e6f5cc
    on contribution (tpo_id);

create unique index unique_tpo_remoteid
    on contribution (tpo_id, remote_id);

create index idx_ea351e15fd9c96b7
    on contribution (tpo_recipient_proxy_id);

create unique index uniq_ea351e15539b0606
    on contribution (uid);

create index idx_ea351e1516fe72e1
    on contribution (updated_by);

create index payment_type_idx
    on contribution (payment_type);

create index donation_contribution_consolidation_idx
    on contribution (payment_account_id, created, gateway, payment_status, amount, discr);

create index idx_ea351e15e7e27f7c
    on contribution (donation_statement_id);

create index idx_contribution_profile_status_account
    on contribution (profile_id, payment_status, payment_account_id);

create index idx_ea351e159f4d1df6
    on contribution (fundraiser_id);

grant select on contribution to readonly_trpc;

