-- auto-generated definition
create table gift
(
    id                     integer generated by default as identity
        primary key,
    donation_id            integer
        references contribution,
    created_by             integer
        references fos_user,
    updated_by             integer
        references fos_user,
    recipient_id           integer
        references profile,
    gift_bulk_id           integer
        references gift,
    gift_fund_id           integer
        references gift,
    coupon_production_id   integer
        constraint fk_a47c990d64868bc9
            references coupon_job,
    migration_key          varchar(32),
    legacy_id              integer,
    parent_legacy_id       integer,
    guid                   varchar(32) not null,
    origin                 varchar(50) not null,
    type                   varchar(50) not null,
    purpose                varchar(32) not null,
    occasion               varchar(255),
    value                  integer,
    metadata               json,
    notify                 boolean,
    status                 varchar(32) not null,
    created                timestamp   not null,
    updated                timestamp   not null,
    deleted_at             timestamp,
    discr                  varchar(20) not null,
    code                   varchar(255),
    code_canonical         varchar(255),
    recipient_name         varchar(255),
    recipient_email        varchar(255),
    message                text,
    comment                varchar(255),
    redemption_date        timestamp,
    payment_date           timestamp,
    gift_data              json,
    is_generated           boolean,
    min                    integer,
    max                    integer,
    unit_count             integer,
    max_value              integer,
    open_value             integer,
    tpo_recipient_proxy_id integer
        references tpo_donor_proxy,
    redeemable_id          integer,
    tree_certificate_id    integer,
    coupon_id              integer,
    redeemed_codes         integer,
    unit_type              varchar(255) default NULL::character varying
);

alter table gift
    owner to u16et197rmd1g5;

create unique index uniq_a47c990d39788ac
    on gift (code_canonical);

create unique index uniq_a47c990d77153098
    on gift (code);

create index idx_a47c990d64868bc9
    on gift (coupon_production_id);

create index idx_a47c990dde12ab56
    on gift (created_by);

create index gift_discr_idx
    on gift (discr);

create index idx_a47c990d4dc1279c
    on gift (donation_id);

create index idx_a47c990d9f15db03
    on gift (gift_bulk_id);

create index idx_a47c990d49f9bc26
    on gift (gift_fund_id);

create unique index uniq_a47c990d2b6fcfb2
    on gift (guid);

create index legacy_id_idx
    on gift (legacy_id);

create unique index unique_legacyid
    on gift (legacy_id, type);

create index migration_key_idx
    on gift (migration_key);

create index idx_a47c990de92f8f78
    on gift (recipient_id);

create index idx_a47c990dfd9c96b7
    on gift (tpo_recipient_proxy_id);

create index idx_a47c990d16fe72e1
    on gift (updated_by);

grant select on gift to readonly_trpc;

