-- auto-generated definition
create table intervention
(
    id                      integer generated by default as identity
        primary key,
    plant_project_id        integer
        references project,
    plant_project_site_id   integer
        references plant_project_site,
    scientific_species_id   integer
        references scientific_species,
    user_profile_id         integer                     not null
        references profile,
    created_by              integer
        references fos_user,
    updated_by              integer
        references fos_user,
    plot_id                 integer
        references plot,
    parent_id               integer
        references intervention,
    origin                  varchar(16)                 not null,
    hid                     varchar(16),
    image                   varchar(255),
    idempotency_key         varchar(64)                 not null,
    device_location         json,
    intervention_date       date,
    registration_date       date,
    intervention_start_date timestamp,
    intervention_end_date   timestamp,
    capture_mode            varchar(32)                 not null,
    capture_status          varchar(32)                 not null,
    geometry                json                        not null,
    original_geometry       json                        not null,
    geometry_updates_count  integer                     not null,
    type                    varchar(32)                 not null,
    measurements            json,
    tag                     varchar(255),
    metadata                json,
    trees_planted           numeric(20, 2)              not null,
    trees_allocated         integer                     not null,
    allocation_priority     varchar(16)                 not null,
    other_species           varchar(2048),
    description             varchar(2048),
    status_reason           varchar(64),
    status                  varchar(32),
    is_private              boolean       default false not null,
    revision_periodicity    json,
    last_measurement_date   timestamp,
    next_measurement_date   timestamp,
    legacy_id               integer,
    deleted_at              timestamp,
    guid                    varchar(32)                 not null,
    created                 timestamp                   not null,
    updated                 timestamp                   not null,
    session_id              varchar(64),
    discr                   varchar(20)                 not null,
    sample_tree_count       integer,
    is_recruit              boolean,
    is_alive                boolean,
    tenant_id               integer
        constraint fk_d11814ab9033212a
            references tenant,
    tree_classification     varchar(255)  default NULL::character varying,
    tree_scientific_name    varchar(255)  default NULL::character varying,
    country                 varchar(5)    default NULL::character varying,
    is_verified             boolean,
    verification_status     varchar(32)   default NULL::character varying,
    verification_sources    varchar(1024) default NULL::character varying,
    comment                 varchar(2048) default NULL::character varying
);

alter table intervention
    owner to u16et197rmd1g5;

create index idx_d11814abde12ab56
    on intervention (created_by);

create index intervention_discr_idx
    on intervention (discr);

create unique index uniq_d11814ab2b6fcfb2
    on intervention (guid);

create unique index uniq_d11814ab7fd1c147
    on intervention (idempotency_key);

create index idx_d11814ab727aca70
    on intervention (parent_id);

create index idx_d11814abe83c4879
    on intervention (plant_project_id);

create index idx_d11814ab310ced23
    on intervention (plant_project_site_id);

create index idx_d11814ab680d0b01
    on intervention (plot_id);

create index idx_d11814ab31861f83
    on intervention (scientific_species_id);

create index idx_d11814ab16fe72e1
    on intervention (updated_by);

create index idx_d11814ab6b9dd454
    on intervention (user_profile_id);

create index idx_d11814ab9033212a
    on intervention (tenant_id);

grant select on intervention to readonly_trpc;

