-- auto-generated definition
create table profile
(
    id                         integer generated by default as identity
        primary key,
    user_id                    integer
        references fos_user,
    created_by                 integer
        references fos_user,
    updated_by                 integer
        references fos_user,
    uid                        varchar(50),
    encryption_key             varchar(255),
    activation_token           varchar(255),
    type                       varchar(50),
    sub_type                   varchar(50),
    name                       varchar(255),
    gender                     varchar(1),
    title                      varchar(50),
    firstname                  varchar(255),
    lastname                   varchar(255),
    address                    varchar(255),
    zip_code                   varchar(50),
    city                       varchar(150),
    geo_longitude              double precision,
    geo_latitude               double precision,
    country                    varchar(2),
    currency                   varchar(3),
    may_publish                boolean,
    may_contact                boolean,
    email                      varchar(100)                                    not null,
    phone                      varchar(50),
    image                      varchar(255),
    is_confirmed               boolean                                         not null,
    is_active                  boolean                                         not null,
    synopsis1                  text,
    synopsis2                  text,
    url                        text,
    link_text                  text,
    created                    timestamp                                       not null,
    updated                    timestamp                                       not null,
    deleted_at                 timestamp,
    discr                      varchar(20)                                     not null,
    is_verified                boolean,
    is_certified               boolean,
    is_deleted                 boolean                                         not null,
    locale                     varchar(20),
    payer_ids                  json,
    payment_setup              json,
    verification_status        varchar(255),
    signup_method              varchar(20) default 'system'::character varying not null,
    guid                       varchar(32)                                     not null,
    has_logo_license           boolean                                         not null,
    tin                        varchar(255),
    session_id                 varchar(64),
    payout_min_amount          integer,
    schedule_frequency         varchar(16),
    salesforce_account_id      varchar(32),
    salesforce_contact_id      varchar(32),
    legacy_id                  integer,
    targets                    json,
    expose_community           boolean     default false,
    legacy_price_till          date,
    supported_profile_id       integer
        references profile,
    slug                       varchar(255)                                    not null,
    display_name               varchar(255)                                    not null,
    address2                   varchar(255),
    payout_day                 varchar(5),
    group_id                   integer,
    is_member                  boolean                                         not null,
    treemapper_migration_state varchar(16) default NULL::character varying
);

alter table profile
    owner to u16et197rmd1g5;

create index idx_8157aa0fde12ab56
    on profile (created_by);

create unique index uniq_8157aa0fe7927c74
    on profile (email);

create index group_id_idx
    on profile (group_id);

create unique index uniq_8157aa0f2b6fcfb2
    on profile (guid);

create unique index uniq_8157aa0fe6e6be
    on profile (salesforce_account_id);

create unique index uniq_8157aa0f7c2c9c4e
    on profile (salesforce_contact_id);

create index idx_8157aa0f922a2b00
    on profile (supported_profile_id);

create index idx_8157aa0f16fe72e1
    on profile (updated_by);

create index idx_8157aa0fa76ed395
    on profile (user_id);

create index idx_profile_type_lastname
    on profile (type, lastname);

grant select on profile to readonly_trpc;

