-- auto-generated definition
create table project
(
    id                         integer generated by default as identity
        primary key,
    tpo_id                     integer
        references profile,
    created_by                 integer
        references fos_user,
    updated_by                 integer
        references fos_user,
    uid                        varchar(64),
    remote_uid                 varchar(255),
    name                       varchar(255),
    synopsis1                  text,
    synopsis2                  text,
    video_url                  text,
    count_target               numeric(14),
    count_planted              numeric(15),
    count_registered           numeric(15),
    count_donated              numeric(16, 2) not null,
    geo_longitude              double precision,
    geo_latitude               double precision,
    country                    varchar(2),
    description                text,
    url                        text,
    link_text                  text,
    geometry                   json,
    tree_cost                  numeric(8, 2),
    currency                   varchar(3)     not null,
    image                      varchar(255),
    survival_rate              smallint,
    is_featured                boolean        not null,
    is_verified                boolean        not null,
    is_certified               boolean,
    is_active                  boolean        not null,
    created                    timestamp      not null,
    updated                    timestamp      not null,
    deleted_at                 timestamp,
    accept_donations           boolean        not null,
    position                   integer,
    is_published               boolean        not null,
    slug                       varchar(255)   not null,
    survival_rate_status       varchar(50),
    tax_deductible_countries   json,
    min_quantity               double precision,
    classification             text,
    tree_count_options         json,
    guid                       varchar(32)    not null,
    prohibit_donations         boolean        not null,
    visitor_assistance         boolean,
    enable_interventions       boolean,
    first_tree_planted         timestamp,
    acquisition_date           integer,
    review_requested           boolean,
    verification_status        varchar(255)   not null,
    fixed_rates                json,
    purpose                    varchar(64)    not null,
    unit_cost                  double precision,
    cost_is_monthly            boolean        not null,
    category                   varchar(64),
    discr                      varchar(20)    not null,
    allocation_priority        varchar(16),
    unit_type                  varchar(255),
    metadata                   json,
    owner_id                   integer
        references profile,
    bouquet_purpose            varchar(64),
    comment                    varchar(255),
    intensity                  smallint,
    revision_periodicity_level varchar(16),
    is_approved                boolean,
    is_top_project             boolean,
    compatibility_key          varchar(64),
    units_contributed          json,
    units_targeted             json
);

alter table project
    owner to u16et197rmd1g5;

create unique index compatibility_key
    on project (country, compatibility_key);

create index idx_2fb3d0eede12ab56
    on project (created_by);

create index project_discr_idx
    on project (discr);

create unique index uniq_2fb3d0ee2b6fcfb2
    on project (guid);

create index idx_2fb3d0ee7e3c61f9
    on project (owner_id);

create unique index unique_remote_uid
    on project (remote_uid, tpo_id);

create unique index uniq_2fb3d0ee989d9b62
    on project (slug);

create index idx_2fb3d0ee22e6f5cc
    on project (tpo_id);

create unique index uniq_2fb3d0ee539b0606
    on project (uid);

create index idx_2fb3d0ee16fe72e1
    on project (updated_by);

grant select on project to readonly_trpc;


