import type { CountryCode } from '@planet-sdk/common';

export type InitialCountryData = {
  name: string;
  trees: number;
};

export const INITIAL_COUNTRY_TREES: Partial<
  Record<CountryCode, InitialCountryData>
> = {
  PH: { name: 'Philippines', trees: 521519 },
  IN: { name: 'India', trees: 408288 },
  US: { name: 'United States', trees: 93455 },
  IE: { name: 'Ireland', trees: 61255 },
  CA: { name: 'Canada', trees: 38114 },
  CO: { name: 'Colombia', trees: 32335 },
  CN: { name: 'China', trees: 19452 },
  MY: { name: 'Malaysia', trees: 17361 },
  TR: { name: 'Turkey', trees: 15643 },
  EG: { name: 'Egypt', trees: 15466 },
  SV: { name: 'El Salvador', trees: 15241 },
  GB: { name: 'United Kingdom', trees: 14059 },
  TH: { name: 'Thailand', trees: 11137 },
  NI: { name: 'Nicaragua', trees: 10665 },
  JP: { name: 'Japan', trees: 8424 },
  ES: { name: 'Spain', trees: 8347 },
  BR: { name: 'Brazil', trees: 8104 },
  NL: { name: 'Netherlands', trees: 6977 },
  DE: { name: 'Germany', trees: 6830 },
  ID: { name: 'Indonesia', trees: 6359 },
  VN: { name: 'Vietnam', trees: 6167 },
  MX: { name: 'Mexico', trees: 6084 },
  CR: { name: 'Costa Rica', trees: 4891 },
  IT: { name: 'Italy', trees: 2977 },
  AU: { name: 'Australia', trees: 2705 },
  PT: { name: 'Portugal', trees: 2234 },
  DO: { name: 'Dominican Republic', trees: 2120 },
  NZ: { name: 'New Zealand', trees: 2117 },
  GT: { name: 'Guatemala', trees: 1800 },
  JM: { name: 'Jamaica', trees: 1762 },
  KR: { name: 'South Korea', trees: 1673 },
  FR: { name: 'France', trees: 1567 },
  HN: { name: 'Honduras', trees: 1543 },
  BG: { name: 'Bulgaria', trees: 841 },
  MU: { name: 'Mauritius', trees: 816 },
  PL: { name: 'Poland', trees: 418 },
  NO: { name: 'Norway', trees: 352 },
  TN: { name: 'Tunisia', trees: 341 },
  GE: { name: 'Georgia', trees: 338 },
  SE: { name: 'Sweden', trees: 295 },
  JO: { name: 'Jordan', trees: 252 },
  SG: { name: 'Singapore', trees: 235 },
  AL: { name: 'Albania', trees: 228 },
  BJ: { name: 'Benin', trees: 148 },
  GR: { name: 'Greece', trees: 122 },
  MA: { name: 'Morocco', trees: 63 },
  AE: { name: 'United Arab Emirates', trees: 62 },
  HU: { name: 'Hungary', trees: 42 },
  CI: { name: 'Ivory Coast', trees: 40 },
  RO: { name: 'Romania', trees: 32 },
  RS: { name: 'Serbia', trees: 16 },
  AR: { name: 'Argentina', trees: 9 },
  ZA: { name: 'South Africa', trees: 8 },
  SK: { name: 'Slovakia', trees: 2 },
};
