export const projects = [
  { id: 1, title: 'Project 1' },
  { id: 2, title: 'Project 2' },
  { id: 4, title: 'Project 3' },
  { id: 5, title: 'Project 3' },
  { id: 6, title: 'Project 3' },
  { id: 7, title: 'Project 3' },
  { id: 8, title: 'Project 3' },
  { id: 11, title: 'Project 1' },
  { id: 12, title: 'Project 2' },
  { id: 41, title: 'Project 3' },
  { id: 51, title: 'Project 3' },
  { id: 16, title: 'Project 3' },
  { id: 71, title: 'Project 3' },
  { id: 83, title: 'Project 3' },
  { id: 190, title: 'Project 1' },
  { id: 290, title: 'Project 2' },
  { id: 47, title: 'Project 3' },
  { id: 564, title: 'Project 3' },
  { id: 63, title: 'Project 3' },
];
